
package es.curso.ws.client.generado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "HolaMundoWSService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8080/_29_WS_SOAP_HolaMundo-0.0.1-SNAPSHOT/HolaMundoWS?wsdl")
public class HolaMundoWSService
    extends Service
{

    private final static URL HOLAMUNDOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOLAMUNDOWSSERVICE_EXCEPTION;
    private final static QName HOLAMUNDOWSSERVICE_QNAME = new QName("http://webservice/", "HolaMundoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/_29_WS_SOAP_HolaMundo-0.0.1-SNAPSHOT/HolaMundoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLAMUNDOWSSERVICE_WSDL_LOCATION = url;
        HOLAMUNDOWSSERVICE_EXCEPTION = e;
    }

    public HolaMundoWSService() {
        super(__getWsdlLocation(), HOLAMUNDOWSSERVICE_QNAME);
    }

    public HolaMundoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLAMUNDOWSSERVICE_QNAME, features);
    }

    public HolaMundoWSService(URL wsdlLocation) {
        super(wsdlLocation, HOLAMUNDOWSSERVICE_QNAME);
    }

    public HolaMundoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLAMUNDOWSSERVICE_QNAME, features);
    }

    public HolaMundoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolaMundoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HolaMundo
     */
    @WebEndpoint(name = "HolaMundoWSPort")
    public HolaMundo getHolaMundoWSPort() {
        return super.getPort(new QName("http://webservice/", "HolaMundoWSPort"), HolaMundo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolaMundo
     */
    @WebEndpoint(name = "HolaMundoWSPort")
    public HolaMundo getHolaMundoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "HolaMundoWSPort"), HolaMundo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLAMUNDOWSSERVICE_EXCEPTION!= null) {
            throw HOLAMUNDOWSSERVICE_EXCEPTION;
        }
        return HOLAMUNDOWSSERVICE_WSDL_LOCATION;
    }

}
