
package es.curso.ws.client.generado;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "HolaMundo", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolaMundo {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mensaje", targetNamespace = "http://webservice/", className = "es.curso.ws.client.generado.Mensaje")
    @ResponseWrapper(localName = "mensajeResponse", targetNamespace = "http://webservice/", className = "es.curso.ws.client.generado.MensajeResponse")
    public void mensaje(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saludo", targetNamespace = "http://webservice/", className = "es.curso.ws.client.generado.Saludo")
    @ResponseWrapper(localName = "saludoResponse", targetNamespace = "http://webservice/", className = "es.curso.ws.client.generado.SaludoResponse")
    public String saludo();

}
